title: Cats and Stuff
author: me :D
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test basically, looking forward to the semester!
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
